[build]
  publish = "public"
  command = "make production-build"

[build.environment]
  HUGO_VERSION = "0.89.4"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/cdeventscon-rsvp"
  to = "https://zoom.us/webinar/register/WN_wQOe7Gw1Sd6wMm5DUMocoQ"

[context.deploy-preview]
  HUGO_ENV = "staging"
  command = "make preview-build"

[context.branch-deploy]
  command = "make preview-build"

[dev]
  framework = "hugo"
  command = "make serve URL=http://localhost:8888/"
